apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jenkins-k8s-role

rules:
- apiGroups: [""]
  resources:
    - pods
    - pods/log
    - pods/exec
    - services
    - secrets
    - configmaps
    - events
  verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch

- apiGroups: [""]
  resources:
    - namespaces
  verbs:
    - get
    - list

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-k8s-rolebinding

subjects:
- kind: ServiceAccount
  name: jenkins
  namespace: default

roleRef:
  kind: ClusterRole
  name: jenkins-k8s-role
  apiGroup: rbac.authorization.k8s.io
